#!/bin/bash

# Source OpenFOAM BASH profile
. /opt/openfoam6/etc/bashrc

# Export fix for OPENMPI in a container
export OMPI_MCA_btl_vader_single_copy_mechanism=none
cd ${0%/*} || exit 1    # Run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

cavityCases="cavity"
LID_SPEED=$1

for caseName in $cavityCases
do
  cd $caseName

  blockMesh

  echo "***** Setting up control parameters ***** "
  checkMesh > out
  MIN_AREA=$(grep -oP '(?<=Minimum face area = )[0-9,.,e,-]+' out)
  echo MIN_AREA "$MIN_AREA"
  MIN_AREA=${MIN_AREA::-1}
  echo MIN_AREA $MIN_AREA
  DELTA_X=$(awk "BEGIN {printf \"%.30f\n\", sqrt($MIN_AREA)}")
  echo DELTA_X $DELTA_X
  DELTA_T=$(awk "BEGIN {printf \"%.30f\n\", $DELTA_X / $LID_SPEED}")
  echo DELTA_T $DELTA_T
  sed -i '' "28s/.*/deltaT          $DELTA_T;/" system/controlDict

  echo "Running $(getApplication)"
  $(getApplication)
  postProcess -func 'vorticity'
  postProcess -func 'enstrophy'
  foamToVTK
done

#------------------------------------------------------------------------------
